name: Hoyo-GameNotice System 00:00

on:
  schedule:
    - cron: "0 17 * * *" # 00:00 (UTC+7)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: Hoyo-GameNotice
          fetch-depth: 0

      # Setup Python
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create settings.json
      - name: Create settings.json
        run: |
          cat > settings.json <<EOF
          {
            "name": "${{ secrets.NAME }}",
            "webhooks": [
              "${{ secrets.WEBHOOK }}",
              "${{ secrets.WEBHOOK1 }}",
              "${{ secrets.WEBHOOK2 }}",
              "${{ secrets.WEBHOOK3 }}",
              "${{ secrets.WEBHOOK4 }}",
              "${{ secrets.WEBHOOK5 }}"
            ],
            "language": "${{ secrets.LANGUAGE }}",
            "repo": "${{ github.repository }}"
          }
          EOF

      # Run scripts
      - name: Execute main scripts
        run: |
          python3 hk4e/main.py
          python3 hkrpg/main.py

      # Read commit message
      - name: Read commit message
        id: commit
        run: |
          if [ -f commit.txt ]; then
            COMMIT_MSG=$(cat commit.txt)
            echo "COMMIT_MSG=$COMMIT_MSG" >> "$GITHUB_ENV"
            echo "Loaded commit message: $COMMIT_MSG"
          else
            echo "commit.txt not found."
          fi

      # Commit & Push
      - name: Commit & Push updates
        if: env.COMMIT_MSG != ''
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add log README.md commit.txt || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "${{ env.COMMIT_MSG }}"

          git pull --rebase origin Hoyo-GameNotice

          git push origin HEAD:Hoyo-GameNotice